### ISSUE TITLE
Including a description in a request/response body with a type destroys information about the type

### ISSUE THREAD

**Issue by wjhsf** [aml-org/amf#1014]
**I'm submitting a ...**
  - [x] bug report

**What is the current behavior?**

Adding a `description` field to a request/response body with a `type` field causes the incorrect value to be returned for the name of the type. In the snippet below, the returned name is `default`, rather than the expected `RequestBody`. Removing the description results in the correct value being returned.
```raml
/endpoint:
  post:
    body:
      type: RequestBody
      description: The request body. This description will break things!
```

**If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

See [this gist](https://gist.github.com/wjhsf/cfa2f0e5502e4c1b7b8a640c271f1619) for a minimal reproduction.
```sh
git clone https://gist.github.com/wjhsf/cfa2f0e5502e4c1b7b8a640c271f1619 demo
cd demo
npm install # or yarn install
npm start # or yarn start
```

**What is the expected behavior?**
If the combination of `type` and `description` is valid RAML, then the name of the type should be accessible.
If the combination is not valid RAML, then the parser should throw an error, rather than returning incorrect information.

**Please tell us about your environment:**
  
  - AMF Version: 4.7.4
  - AMF Distribution: JS 
  - Operating System: macOS
  - Link to your project: [This gist](https://gist.github.com/wjhsf/cfa2f0e5502e4c1b7b8a640c271f1619)

**Other information**

This issue is blocking the release of the [commerce SDK](https://github.com/SalesforceCommerceCloud/commerce-sdk).

**Comment by nschejtman** [comment]
Hello @wjhsf 
This is in fact an expected behavior. By adding a new `description` facet the type is no longer the same exact type as `RequestBody`. This means we are creating a new type which inherits all the facets from `RequestBody` and defines its own `description` facet. This is why the new type has another name. The `description` facet might seem superfluous but from an AMF standpoint it is no different from say a `properties` facet. 

Closing this issue. If you can provide some justification for this behavior being a bug feel free to re-open it.
