### ISSUE TITLE
Validation fails for a valid API spec

### ISSUE THREAD

**Issue by anandsgar-sap** [aml-org/amf#1305]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**

Try to validate [openapispec.json](https://github.com/aml-org/amf/files/8038305/openapispec.json.txt)
with below code:

  > const oas30Client = OASConfiguration.OAS30().baseUnitClient();
  >  const parsedApiResult = await oas30Client.parseContent(apiSpec);
  >  const validateResult = parsedApiResult.conforms ? await oas30Client.validate(parsedApiResult.baseUnit) : parsedApiResult.conforms;
  > console.log(validateResult &&  validateResult.conforms);

Observed an error stating : 'Unresolved reference '#/components/parameters/count'',

* **What is the expected behavior?**

Above API spec seems to be valid (validated in swagger)

* **Please tell us about your environment:**
  
  - AMF Version: - 5.0.3
  - AMF Distribution: JVM or JS  --- JS
  - Operating System: Any

**Comment by looseale** [comment]
Hi.

There is a problem with the API: you are using a ref to a parameter in a place that make non sense to use it. You should have a reference to a schema there instead.
AMF only search references where the definition is allowed (e.g. you are referencing that parameter in a `parameters` section and it is working there).

To fix this you could extract the parameter schema to a declaration in `components/schemas` and reference it from there in both cases, from the parameter and the from the properties; or change the references in the properties to point to the schema inside the parameter (`#/components/parameters/count/schema`).

AMF is more strict than other Swagger validators. Maybe the other validator is resolving the ref, but for sure no key is matching after that, it is leaving an empty schema there and it will not work as you want (if you compare the structure of a parameter with the structure of an schema you will see that there is no common keys).

**Comment by anandsgar-sap** [comment]
Hi @looseale 

I had a chat with a colleague and we could observe following:

If parameters cannot be provided in $ref, how come the validator is not erroring the below $refs
{ "$ref": "#/components/parameters/top" },
{ "$ref": "#/components/parameters/skip" },
{ "$ref": "#/components/parameters/search" },
 
& failing only for count $ref:
{ "$ref": "#/components/parameters/count" },
 
Also, please refer to the SPEC : https://spec.openapis.org/oas/v3.1.0#components-object  It  states components can have parameters which are reusable. So why is it wrong then to have $ref to a parameter?

**Comment by looseale** [comment]
Hi @anandsgar-sap 

I didn't said you cannot reuse parameters, I said you should reference them only from a valid place.

Taking your API and the `$ref` to `"#/components/parameters/count"` as example:
In line 29, the ref to that parameter is correct and no error is shown. In that case you are using a `$ref` to the parameter inside a `parameters` inside an `operation`, that is a `parameter object` node (https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#parameterObject) and it is totally valid.
In the case where the errors are shown (line 140 and 327), you have a `$ref` to a parameter in the definition of a `property` inside an `object`. That is a `schema object` node (https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#schema-object), and that reference is not valid there. You should have a `$ref` to a schema in that place (defined in `#/components/schemas` or in other place of the API).

As I said in the previous message, even though AMF resolve the `$ref` there, the content of a parameter is invalid in those places (line 140 and 327): you could check the 2 links to the specs (the ones of the parameter object and the schema object) and you will see that most of the keys of a parameter object are invalid in a schema object node.

I hope I have clarified your concerns, any doubt let me know.

**Comment by jagadish-kb** [comment]
HI @looseale  
    I dont find your assumption in this [section](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#schema-object) of Spec. Rather as per the spec definition of schema object, please find the below w.r.t Reference Objects usage in its place:

_Alternatively, any time a Schema Object can be used, a  [Reference Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#referenceObject)  can be used in its place. This allows referencing definitions instead of defining them inline._

And per the definition for [Reference Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#referenceObject), - The Reference Object is defined by [JSON Reference](https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03#section-3) and follows the same structure, behavior and rules. 

So i dont see anywhere in the OpenAPI spec mentioning that '$ref' in `components/schemas`  must refer back within `components/schemas` . All the spec mentions is that it needs to be a valid JSON reference (i.e. a valid JSON URI reference) which in the above example is valid. Looks like AMF is making this wrong assumption that all $refs within schema objects must be found within `#Components/Schema` which is incorrect per specification. Why cant $ref be treated uniformly ? why cant it be resolved the same way in LN140 and LN327, as its resolved on LN29 ? Why is this distinction being made when the spec isn't saying it so?

Also, please note the spec provided in this bug is autogenerated via the Odata to OpenAPI spec generator (our internal tool maintained by another team). So the generator is as well following the specification & not just that the swagger validator is lenient. Count is defined as a data type in parameter and why shouldn't it be referenced once again within a complex data structure within schema object. Asking it to be redefined once again within schema isn't the right resolution -  imagine all parameters having to be redefined within schemas object once again leading to duplication of types definition. 

I  believe this can be simple fix on AMF side to validate $ref as per the definition for [Reference Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#referenceObject) as mentioned in OpenAPI spec rather than just limiting them to be within schema object, which isn't right.

**Comment by looseale** [comment]
Hi @jagadish-kb 
We have this distinction in resolving `$ref` for performance. We pre-compute all schemas in a map and then resolve the references in schema nodes using that map. We do this because traversing the API each time to resolve JSON references is very time-consuming in big APIs and the API will be invalid anyway.

For example, this is a reduced case of your API:

```
{
  "openapi": "3.0.2",
  "info": {
    "title": "some title",
    "description": "some description",
    "version": ""
  },
  "paths": {
    "/Risks": {
      "get": {
        "responses": {
          "200": {
            "description": "Retrieved risks",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "@odata.count": { "$ref": "#/components/parameters/count" }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "count": {
        "name": "$count",
        "in": "query",
        "description": "something",
        "schema": { "type": "boolean" }
      }
    }
  }
}
```

This shows an error `Unresolved reference '#/components/parameters/count'` at line 19, for the reason I explain in the previous message.

We will not make the change, but hypothetically, if that `$ref` were resolved, you will end with a resolved API like this:

```
{
  "openapi": "3.0.2",
  "info": {
    "title": "some title",
    "description": "some description",
    "version": ""
  },
  "paths": {
    "/Risks": {
      "get": {
        "responses": {
          "200": {
            "description": "Retrieved risks",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "@odata.count": {
                      "name": "$count",
                      "in": "query",
                      "description": "something",
                      "schema": { "type": "boolean" }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "count": {
        "name": "$count",
        "in": "query",
        "description": "something",
        "schema": { "type": "boolean" }
      }
    }
  }
}
```

And this API is still invalid: `in` and `schema` are not valid keys in that place. Also, that schema doesn't have `type`. You still will have errors there, different ones, but the API is still invalid at the end.

I agree it is not exactly what the spec says about references resolution, but we choose to have better performance in valid APIs than more specific errors in invalid ones.
