### ISSUE TITLE
AMF5 uses commons.io 1.4, which is vulnerable

### ISSUE THREAD

**Issue by jgsuess** [aml-org/amf#1405]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] question
  - [x] other

* **What is the current behavior?**
AMF transitively depends on [`org.apache.commons.io`](https://mvnrepository.com/artifact/commons-io/commons-io/1.4) which is vulnerable to a path traversal exploit.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

* **What is the expected behavior?**

Review to be performed or dependencies to be updated to avoid exploit.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

Avoid intrusion risk in server use.

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.8
  - AMF Distribution: JVM
  - Operating System: Ubuntu 20.04
  - Link to your project: internal

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by tomsfernandez** [comment]
HI @jgsuess! Sorry for the wait. The only internal sbt module that has a dependency on `org.apache.commons.io` is the adhocCli artifact which we use internally for a very specific test suite. This shouldn't make users that depend on the `amf-cli` or other modules vulnerable to commons-io exploits.

We regularly scan the project in search of vulnerable dependencies. We will setup a "Security Policy" in this repository so that the next time, you can report a vulnerability through there.

Thanks for contributing!
