### ISSUE TITLE
unable to read host and basePath after parsing OAS2.0 file using AMF parser

### ISSUE THREAD

**Issue by manisharma07** [aml-org/amf#1443]
I'm submitting a question here, 
we're parsing OAS2.0 spec file using AMF client
Document doc = (Document)OASConfiguration.OAS20().baseUnitClient().transform(model).baseUnit();

We're unable to find host and basePath field in the **doc** generated, 
![image](https://user-images.githubusercontent.com/97285218/173524620-36681f9e-2471-47df-b14d-6cfd5dd55857.png)

for OAS3,0 we get it under servers, 
  
  - AMF Version: 5.0.1
  - AMF Distribution: JVM
  - Operating System: Windows

**Comment by nschejtman** [comment]
Hi @manisharma07,
this is because in OAS 3.0 we propagate servers down to the operations. You can take a look at the code here: [ServersNormalizationStage](https://github.com/aml-org/amf/blob/develop/amf-api-contract/shared/src/main/scala/amf/apicontract/internal/spec/common/transformation/stage/ServersNormalizationStage.scala). You can resolve with the Editing pipeline, that will still propagate but keep the original definition at the WebApi level. 

Just a quick side note: the AST explorer on you screenshot does not call `.transform` only `.parse` (behaves differently to your code)
