### ISSUE TITLE
Missing customDomainProperties of Shapes obtained via UnionShape.anyOf

### ISSUE THREAD

**Issue by brennana** [aml-org/amf#1502]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**
It appears that the obtainable customDomainProperties of a given shape are actually those of a UnionShape, if that Shape is explicitly obtained via that UnionShape's `anyOf`, particularly when the UnionShape declares its own customDomainProperties.

So, if a UnionShape does not have a specific customDomainProperty, then it will not appear in child types via `anyOf` (though the shape as declared still contains its original customDomainProperties). If, however, the UnionShape does contain the property, it will show up in the child type via `anyOf`, but only with the value set in the UnionShape itself.

Finally, I find that if the UnionShape *does not declare any customDomainProperties whatsoever*, then the child types via `anyOf` contain their own customDomainProperties as expected.

The following test code logs the difference in customDomainProperties of `Type2`, depending on how we retrieve the Shape object.

```js
const amf = require('amf-client-js')

async function test () {
  const ramlStr = `
  #%RAML 1.0

  annotationTypes:
    complex:
      allowedTargets: TypeDeclaration
      type: object
      properties:
        //: string
    flag:
      type: nil
      allowedTargets: TypeDeclaration

  types:
    Type1:
      (complex):
        foo: "bar"
        fizz: "buzz buzz"
      (flag):
      type: object
      properties:
        type1prop: string
    Type2:
      (flag):
      (complex):
        foo: "bar"
        yeah: "ok then"
      type: object
      properties:
        type2prop: string
    Type3:
      (flag):
      (complex):
        foo: "bar"
        nah: "nothing much"
      type: object
      properties:
        type3prop: string
    Union:
      (flag):
      (complex):
        lol: "pls no"
      type: Type1 | Type2 | Type3
  `

  const raml10 = amf.RAMLConfiguration.RAML10().baseUnitClient()
  const parseResult = await raml10.parseContent(ramlStr)
  const resolved = raml10.transform(parseResult.baseUnit, amf.PipelineId.Cache).baseUnit

  const type2Annotations = resolved.declares[3].customDomainProperties.map((d) => `${d.name.value()}: ${d.extension.properties && Object.keys(d.extension.properties).toString()}`),
        type2AnnotationsViaUnion = resolved.declares[5].anyOf[1].customDomainProperties.map((d) => `${d.name.value()}: ${d.extension.properties && Object.keys(d.extension.properties).toString()}`)

  console.log(type2Annotations)
  console.log(type2AnnotationsViaUnion)
}

test()
```

* **What is the expected behavior?**
I expected the Shape to have its actual customDomainProperties as declared, regardless of how the Shape object is obtained, and regardless of whether the UnionShape sets its own customDomainProperties. The RAML specification does not seem to say that this behavior is warranted, either.

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.10
  - AMF Distribution: JS 
  - Operating System: Linux x86_64

**Comment by arielmirra** [comment]
Hi @brennana! This is definitely a bug. I've reported it in our system with the identifier `W-11567107`. I'll keep you up-to-date with any changes made. Thank you!

**Comment by tomsfernandez** [comment]
Hi @brennana. A few findings:

- The way you access shapes affects the output because the Type1 you access via the "declarations" and the one you access via the union **are not the same shapes**. They have different ids. Why are they different shapes ? In ShapeNormalization, the elements of a union are copied to avoid mutating the "original" ones.

- Why do we modify copies ? It is easier for validation engines to validate a payload against a union if the members of the union already have all necessary facets to validate the payload. If not validation would go from:

validation = (payload & member1) || (payload & member2) || (payload & member3)

to:

validation = ((payload & member1) || (payload & member2) || (payload & member3)) && unionFacets

- The spec states that a union can define extra facets if they are compatible with all members of the union.

> A union type MAY use facets defined by any of its member types as long as all member types in the union accept those facets.

The thing is, it doesn't specify wether the facets are replaced or can co-exist. This brings a question: what if facet co-existance causes a validation contradiction ?

In this case as the union and its members define customDomainProperties we are ignoring the ones in the union members and applying the ones defined for the union to each member.

For example: for the customDomainProperties field, should we concatenate the property members ? If two members are defined by the same key, should merge their values or should we just replace customDomainProperties with the same name?

It is a complicated behaviour to change because of backwards compatibility reasons. We will have to have further internal discussions to see wether we will change this now or we wait until a next major release.

**Comment by gutee** [comment]
This issue is done.
