### ISSUE TITLE
Validation stage tampers the parsed model

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1749]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

When validating the parsed model, validation stage seems to apply transformations that change the base model. This seems to me as unexpected behavior as I usually want to validate the model before continuing with my own code.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

The following code demonstrates that information about inherited type is absent from the base model (possibly got resolved) after validation stage.
```js
import amf from 'amf-client-js'
import { assert } from 'console';

(async () => {
    const raml = `
#%RAML 1.0 Library

types:
    BaseAnnotatedType:
        type: object

    AnnotatedType:
        type: BaseAnnotatedType
    `

    const client = amf.RAMLConfiguration.RAML10().baseUnitClient()

    const before = await client.parseContent(raml)
    const annotatedType = before.baseUnit.declares.find(item => item.name.value() === 'AnnotatedType')
    console.log('Check before validation.\n')
    assert(annotatedType.inherits.length === 1, "Information about inheritance is absent.")

    const beforeValid = await client.validate(before.baseUnit)
    console.log(before.merge(beforeValid).toString())

    console.log('\nCheck after validation.')
    assert(annotatedType.inherits.length === 1, "Information about inheritance is absent.")
})()
```

The output:
```
Check before validation.

Model: http://a.ml/amf/default_document
Conforms: true
Number of results: 0


Check after validation.
Assertion failed: Information about inheritance is absent.
```

* **What is the expected behavior?**

The base model must stay as is after validation stage.

* **Please tell us about your environment:**
  
  - AMF Version: 5.2.5
  - AMF Distribution: JS 
  - Operating System: Windows 10 22H2

**Comment by tomsfernandez** [comment]
Hi @deiteris. Yes, we are aware of this but this is an expected behaviour for us.

**Why is this an expected behaviour?** To be able to validate APIs we must perform a series of transformations on them like applying resource types and traits, RAML inheritance, securityScheme resolution and so on.

This isn't the clearest behaviour as one would expect that validation doesn't transform the model like you did. As I said before, we can't do that.

A question that comes up is: why doesn't the AMF validator make a copy of the model before validating it ? We do that for performance reasons. There are clients that they toss the model after validating it so they don't want to suffer the performance impact of copying big parsed models.

We should improve our documentation to state this. You will see that this mutation may happen in other AMF operations like rendering and transformation.

To work around this, you can clone the BaseUnit by running something like:

```typescript
const unit: BaseUnit = // parseUnit
const cloned: BaseUnit = unit.cloneUnit()
```

Hope this helps. Please ask if this isn't clear enough.

**Comment by deiteris** [comment]
Hi @tomsfernandez. Okay, I was also looking for a method to copy the base unit to workaround this and this helps greatly in this case. Thanks!
