### ISSUE TITLE
Is there a way to resolve only types?

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#559]
Using amf-client-js@3.5.4 it's possible to resolve types without losing their definitions in the API root using `editing` pipeline.
But is there a way to resolve ONLY types in API document and not put them as inline type declarations to endpoints?

E.g. code [1] outputs [2]. I'm trying to make it produce [3].

[1]
```js
const amf = require('amf-client-js')


const ramlStr = `#%RAML 1.0
types:
  Animal: string
  Cat: Animal

/cats:
  get:
    responses:
      200:
        body: Cat[]
`

async function main () {
  await amf.AMF.init()

  const model = await (new amf.Raml10Parser()).parseStringAsync(ramlStr)
  const resolver = amf.Core.resolver('RAML 1.0')
  const resolved = resolver.resolve(model, 'editing')
  const generator = amf.AMF.raml10Generator()
  const gen = await generator.generateString(resolved)
  console.log(gen)
}

main()
```

[2]
```raml
#%RAML 1.0
types:
  Animal:
    type: string
  Cat:
    type: string
/cats:
  get:
    responses:
      "200":
        body:
          items:
            type: string
```

[3]
```raml
#%RAML 1.0
types:
  Animal:
    type: string
  Cat:
    type: string

/cats:
  get:
    responses:
      200:
        body: Cat[]
```

**Comment by gutee** [comment]
Hi, there is currently no way of doing this, as the first thing that is resolved is the references so that we can resolve the shapes with no linking in the middle. Also, overlays, extensions, traits and resource types should be applied.
A pipeline to resolve only the declarations wouldn't work because we would have to traverse all the model and replace the links to the shapes with the new resolved ones.
