### ISSUE TITLE
Universal way to check if annotation is applied?

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#561]
Lets say I have a following API [1]. Is there a _universal_ way to see if a declaration has annotation `(customName)` applied to it?
I can dig into objects by following their structure but I'm looking for something that would let me treat all the objects the same way no matter their structure.

[1]
```raml
#%RAML 1.0
title: Product API

annotationTypes:
  customName:
    type: string

resourceTypes:
  item:
    usage: Details of a single resource

    get:
      displayName: Item details
      description: Get details for a single item
      (customName): Hello

traits:
  hasErrorResponse:
    responses:
      500:
        description: Error processing request.
        headers:
          x-correlation-id:
            type: CorrelationId

        body:
          application/json:
            type: object
            displayName: Inline Error Response
            (customName): World
            additionalProperties: false
            properties:
              field1:
                type: string
              field2:
                type: string
```

**Comment by gutee** [comment]
Hi, all objects in amf model inherit from DomainElement which has a CustomDomainProperties field that has the raml annotations. Is this what you need?

**Comment by postatum** [comment]
> Hi, all objects in amf model inherit from DomainElement which has a CustomDomainProperties field that has the raml annotations. Is this what you need?

Yes, but in this example, when I get the `hasErrorResponse` trait, it's `CustomDomainProperties` is empty. I can only get that annotation when I go deep into its `properties` like so https://github.com/raml-org/webapi-parser/issues/48#issuecomment-548226590

**Comment by gutee** [comment]
Yes, that is correct. This is because in the case of the trait, the annotation `customName` is not applied to the declaration, it is applied directly to the type inside the payload. This is when the trait or resource type is applied.

But remember that when you access the trait or the resource type (raw value, the declaration, not the application of it), this is a macro, this means it is a dynamic AST node, that is why it is composed of DataNodes, it has not been parsed yet to be applied.
