### ISSUE TITLE
`Shape.inherits` is discarded during resolve with editing pipeline

### ISSUE THREAD

**Issue by kdubb** [aml-org/amf#967]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

During resolve with editing pipeline , `Shape.inherits` is discarded.  It doesn't appear to be "moved" to another property or set of properties.

It appears it is currently impossible to recover the inheritance information after resolution.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

After parsing & resolving with `EDITING_PIPELINE`:
```kotlin
val parsed = Raml10Parser(environment).parseFileAsync(uri).get()
val resolved = Raml10Resolver().resolve(parsed, ResolutionPipeline.EDITING_PIPELINE())
```

All of the `Shape.inherits` in the `resolved` document will return empty lists. 

* **What is the expected behavior?**

With the "editing" pipeline, this information is expected to be retained. The description of the editing pipeline says:

    Keeps all information in already parsed nodes, such as the source and the declarations

This is very important information that is not being retained.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.3
  - AMF Distribution: JVM
  - Operating System: macOS
  - Link to your project: https://github.com/outfoxx/sunday-generator

**Comment by arielmirra** [comment]
Hi @kdubb! This is the expected behaviour when resolving type definitions. The documentation regarding editing pipeline may lead to confusions, and we'll look into that and update it with more details, thanks for the catch. But to be more specific, it refers to maintaining information regarding referenced documents as well as type declarations.

Resolving shapes is key part of resolution pipelines, and this includes resolving inheritance. The purpose of resolution is to make the graph nodes more self-contained, that's why Shape.inherits is applied and discarded.

Finally, could you elaborate more on the use case you have? I couldn't get the gist of what are you using the inheritance for or why you need it in the resolved model.

Thank you again!

**Comment by kdubb** [comment]
@arielmirra The Sunday generator has an option to generate class hierarchies that match "simple" RAML inheritance. We are defining "simple" inheritance to be when all the types in an inheritance hierarchy inherit from a single type.

Currently, the generator code uses unresolved documents (with lots of manual resolving) and we are able to recover the inheritance hierarchy using `Shape.inherits`. This has a few problems, the manual resolving code notwithstanding, but now we know that overlays aren't supported at all; which is a deal breaker.

During resolution, an internal `InheritedShapes` annotation is added which, at first glance, seems to help. Unfortunately none of the ids in it are able to be found in the resolved document.

**Comment by arielmirra** [comment]
I see, what do you mean when you said "overlays aren't supported at all"?  I'm trying to get all the info about how are you using the inherits and the annotation IDs.

**Comment by kdubb** [comment]
I only meant that without resolving a document (as we are currently doing), the overlays are not applied. I understand that we should be using a resolved document, and we want to, but we need the inheritance information in some fashion.

**Comment by kdubb** [comment]
@arielmirra Is there a workaround that you can suggest? This issue the last major hurdle for us. We need to be able to use resolved documents _and_ have access to the inheritance information in some fashion.

**Comment by arielmirra** [comment]
Hi @kdubb! A couple of things I'd like to mention.

Regarding the documentation, thanks to this issue we're working on updating it to make more clear what the editing pipeline does and what resolution stages are in every pipeline. That's being tracked in the internal issue [APIMF-3137](https://www.mulesoft.org/jira/browse/APIMF-3137) (attached for history's sake, only the team can see it).

Regarding the `InheritedShapes` annotation IDs not being found, we've created an issue to look deeper into that, test that indeed there's something there, as it's a legacy annotation that's not being used. That's being tracked in the internal issue [APIMF-3135](https://www.mulesoft.org/jira/browse/APIMF-3135).

If you want to provide more code or information about how you're using the IDs, or anything you think should be useful, feel free to do so.

I'll keep the issue open until we gather more information about this specific use case. I'll keep you posted when this issue is assigned, if we find something, or when we have a release version where this is fixed/changed.

**Comment by kdubb** [comment]
>If you want to provide more code or information about how you're using the IDs...

I am attempting to use the IDs from the `InheritedShapes` annotation with `BaseUnit.findById` to lookup the directly inherited shapes for any given shape, in a resolved document.

According to the code in `ShapeCanonizer.canonicalInheritance` the `InheritedShapes` annotation saves this information we need. Unfortunately the ids stored in here seem to be removed from the resolved document.

**Comment by kdubb** [comment]
@arielmirra The change in PR #983  makes `InheritedShapes` usable for us in the final resolved document.

Here is some code (in Kotlin) I am using to test out printing the inheritance hierarchy. Without the changes in PR #983, this will always print `Not Found` for all of the ids found in `InheritedShapes`.

Note: It uses extension methods on `BaseUnit` to make it more readable. I've added those definitions below.

```kotlin
// Loop through every declared `Shape` element in any `BaseUnit`
// (specifically including any units referenced by the document)
//
// Uses `allDeclaredModels` extension method

val allDeclaredShapes = document.allDeclaredModels.flatMap { it.declares }.filterIsInstance<Shape>()
for (shape in allDeclaredShapes) {

  printHierarchy(shape)

}

// Recursively prints the hierarchy reported by `InheritedShapes`
//
fun printHierarchy(shape: Shape, indent: String = "") {
  
  print("$indent|-> ${shape.name}")

  // Find InheritedShapes annotation
  val inheritedShapes =
    shape.annotations._internal()
      .find(InheritedShapes::class.java)
      .getOrElse<InheritedShapes?> { null }

  // If we have do not have any inherited shapes, exit
  if (inheritedShapes == null || inheritedShapes.baseIds().isEmpty) {
    println()
    return
  } else {
    println(":")
  }

  for (inheritedShapeId in inheritedShapes.baseIds()) {

    // Attempt to find the referenced inherited shape in any `BaseUnit`
    // (specifically including any units referenced by the document)
    //
    // Uses `findInAnyUnitById` extension method

    val inheritedShape = document.findInAnyUnitById(inheritedShapeId) as? Shape

    // If we found the inherited shape, recursively
    // continue printing the hierarchy
    if (inheritedShape != null) {
      printHierarchy(inheritedShape, "$indent  ")
    } else {
      println("$indent  |-> NOT FOUND")
    }
  }
}
```

#### Input
Using the following RAML as input:
https://github.com/outfoxx/sunday-generator/blob/f252cd5285d7f504e777661429085480f2cb586c/generator/src/test/resources/raml/type-gen/types/obj-inherits.raml

#### Output
Using version `4.7.3`/`4.7.4-RC.3`, it fails to find any ids saved in `InheritedShapes`.
```
|-> Test

|-> Test2:
  |-> NOT FOUND

|-> Empty:
  |-> NOT FOUND

|-> Test3:
  |-> NOT FOUND
```

Using PR #983, it correctly traverses the inheritance hierarchy
```
|-> Test

|-> Test2:
  |-> Test

|-> Empty:
  |-> Test2:
    |-> Test

|-> Test3:
  |-> Empty:
    |-> Test2:
      |-> Test
```

#### Extension methods:

```kotlin
// Collect all referenced documents into flat list
val BaseUnit.allUnits: List<BaseUnit> get() = references.flatMap { it.allUnits }.plus(this)

// Collect all units that implement `DeclaresModel`
val BaseUnit.allDecelaredModels get() = allUnits.mapNotNull { it as? DeclaresModel }

// Find an element by id, in any unit; including referenced units
fun BaseUnit.findInAnyUnitById(id: String): DomainElement? {
  for (unit in allUnits) {
    val found =  unit.findById(id)
    if (found.isEmpty) {
      continue
    }
    return found.get()
  }
  return null
}
```

**Comment by kdubb** [comment]
After further testing PR #983 doesn't properly save the information we are looking for when using overlays & fragments & documents all together.

I am at a loss and this brings our project to a standstill until we find a proper solution.

**Comment by tomsfernandez** [comment]
Sorry for the wait. We have to fix this from our side but it won't be easy. 

Internal ticket link: https://www.mulesoft.org/jira/browse/APIMF-3153.

We will be posting updates in this Github thread.

**Comment by kdubb** [comment]
@tomsfernandez Is there any update on this? It's very limiting to releasing a fully working version.

Also, I've done some hacking on the library already, maybe if you pointed in a general direction I could help implement the necessary changes.

**Comment by tomsfernandez** [comment]
Hi @kdubb, sorry for the slow response. Right now we don't have the manpower to fix this as we are focusing on releasing a new major version. I would gladly point you to where this can be done but there is an internal change of the new version that will probably break what you do.

We will know in these weeks if it will break or not. If you want I can write to you then and point where the fix can be made.

**Comment by kdubb** [comment]
@tomsfernandez Wondering if there is any movement on this.  We've migrated to the 5.x version but we're still plagued by the same issue.

Now that the new version is more settled, is pointing me in the right direction to update/fix this issue now viable?

**Comment by tomsfernandez** [comment]
@kdubb sorry for the long time to respond. 

The issue you have is caused by: 
https://github.com/aml-org/amf/blob/a574e1e13ca21d9f9130a20ce1ccffeff89a0181/amf-shapes/shared/src/main/scala/amf/shapes/internal/domain/resolution/shape_normalization/ShapeCanonizer.scala#L142.

It isn't straightforward at all as this is part of an overly-complex caching mechanism to avoid re-canonizing shapes. We are doing an effort now to make the overall recursion/canonization process much more simple but we haven't succeded yet.

Please ask if you have any troubles.

(Edit):

I see two possible paths here:
-  Assure that the Id pointed by the InheritanceProvenance annotation is correct. (Should be the easiest solution but definitly the most fragile)
- Build something to circunvent the inheritance caching mechanism to avoid caching inheritances. Just erasing that line will probably end up in different json-lds (not necesarilly incorrect) or never ending executions.

**Comment by kdubb** [comment]
@tomsfernandez I've played around with this and cannot seem to get it to work. Any chance this could be added to your internal schedule sometime soon?

**Comment by tomsfernandez** [comment]
@kdubb Hi! Last week we did an analyzed this issue. We found out the general cause but it require a lot of effort to solve, as you have surely seen, the part of the code that solved type inheritance is quite complex and difficult to debug and read. We don't have it scheduled yet but as I said before, we have an initial analysis of what a solution would be like and the problems we will face. Sorry that I can't provide you an exact and definitive date for this yet.

**Comment by gutee** [comment]
Old issue. Closing after workaround.

**Comment by kdubb** [comment]
@gutee What is the workaround?

**Comment by kdubb** [comment]
@gutee @tomsfernandez Can anybody enlighten me as to what this workaround is?
